apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: k3s-ingress-dns
  namespace: external-dns
spec:
  endpoints:
  - dnsName: triplembiz.com
    recordTTL: 300
    recordType: A
    targets:
    - 204.216.209.70
  - dnsName: cd.triplembiz.com
    recordTTL: 300
    recordType: A
    targets:
    - 204.216.209.70
